version: '3.6'

services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: DEV-Postgres-LikeThisMovie
    env_file: ./env/.postgres-dev.env
    volumes:
      - devPostgresLikeThisMovie:/var/lib/postgresql
    ports:
      - 5432:5432

  postgres-test:
    image: postgres:15-alpine
    container_name: TEST-Postgres-LikeThisMovie
    env_file: ./env/.postgres-test.env
    volumes:
      - testPostgresLikeThisMovie:/var/lib/postgresql
    ports:
      - 5433:5432

volumes:
  devPostgresLikeThisMovie:
  testPostgresLikeThisMovie: